bitcoin-core-review-club/website

_posts/2019-07-05-#15443.md
Add PR 15443 for 2019-07-05 meeting
=> add PR 15443

_data/settings.yml, _includes/header.html, index.html, previous_meetings.html
Also adds links to 'home' and 'previous_meetings' in the header.
=> Add previous_meetings.html page

_posts/2019-09-25-#16202.md
Don't hesitate to suggest changes or improvements.
I force-pushed a few edits after review.
=> n16202: add notes and questions

_posts/2019-09-25-#16202.md
and (perhaps controversially) update an imprecise answer of mine to not send people looking in the wrong place.
=> n16202: add p2p encryption core dev transcript

_data/settings.yml, index.html, meetings-components.html, meetings-hosts.html, meetings.html
This should fix the links to pretty urls
=> Add permalinks

_posts/2019-10-02-#16401.md
Feel free to correct or improve!
=> n16401: add notes and questions

assets/css/all.sass
There's currently a lot of padding/margin around the page. Reduce it.
=> Reduce site padding

Gemfile, Gemfile.lock, README.md, Rakefile, index.html
This PR adds a Ruby make (rake) command to run from root or `/_posts`, that creates a new post file:
```
$ rake posts:new -- --help
Usage: rake posts:new -- <options>
-p, --pr NUMBER                  Pull request number (required)
-h, --host USERNAME              Host's GitHub username (required)
-d, --date YYYY-MM-DD            Meeting date in ISO8601 format (optional, defaults to next Wednesday)
-H, --help                       Display this help
$ rake posts:new --pr 16402 --host jnewbery
New post file _posts/2019-10-09-#16402.md created successfully.
```
Args are order-independent.
`--pr` and `--host` are required and an error is signalled if they are omitted.
If no date is passed, it is automatically set to the upcoming Wednesday and a message is printed.
If the file already exists: …
=> Ruby make command to create a new post

README.md
FWIW, do you plan to rename the repository?
=> Update README with new website

Gemfile.lock
Hopefully this fixes netlify builds
=> remove 'BUNDLED WITH' from Gemfile.lock

_posts/2019-10-16-#16279.md, _posts/2019-10-23-#15934.md
Also add the PR number to 16279 title
=> 2019 10 add n15934

_posts/2019-10-23-#15934.md
=> minor fix to n15934

index.html
update time to be one hour later as per convo at the end of last weeks meeting
=> update meeting time

_posts/2019-11-06-#15845.md
Thanks to Adam Jonas for reporting.
=> Fix false positive mistake

_posts/2019-05-01-#15557.md, _posts/2019-05-08-#10823.md, _posts/2019-05-15-#15834.md, _posts/2019-05-22-#15450.md, _posts/2019-06-05-#16060.md, _posts/2019-06-19-#15481.md, _posts/2019-07-24-#15713.md, _posts/2019-08-21-#15931.md, _posts/2019-09-04-#16512.md, _posts/2019-09-25-#16202.md, _posts/2019-10-23-#15934.md, _posts/2019-11-06-#15845.md, _posts/2019-11-13-#17303.md
=> Add Meeting Log for n17303

CONTRIBUTING.md, README.md, index.html
We've had quite a few guest hosts for the PR review club. I wanted to collect together some of what we've learned so any future hosts can benefit from our experience.
This PR adds a new CONTRIBUTING.md file with some general tips for hosting.
=> Add tips for review club hosts

index.md
- fix CONTRIBUTING.md URL
- add links to freenode and the Bitcoin Core review process
- add a bit more space between the questions and answers
- remove a bit of redundant text
- very minor spelling/punctuation
- refer to the review club in a consistent manner (the review club vs Review Club)
- the productivity tips and developer notes were split off a few months ago; add links to both
Feel free to pick and choose.
=> Home page suggestions

_posts/2019-12-11-#16702.md
and move the misplaced "asmap effect analysis script" paragraph from the bottom back into the Notes section.
=> Improve n16702 notes & questions

_posts/2019-12-11-#16702.md
I've also included the discussion prior to the meeting about testing and removed an expletive.
=> Add n16702 meeting log

assets/css/all.sass, index.md, meetings-components.html, meetings-hosts.html, meetings.html
=> Fix vertical alignment of PRs

_posts/2019-12-18-#17639.md
Thought: Feel free to close this PR if you prefer to push the log from your local timezone to maintain meeting time consistency.
=> Add meeting log for n17639

CONTRIBUTING.md
=> CONTRIBUTING.md: additions and edits

CONTRIBUTING.md
Some ideas from last meeting's postmortem!
=> doc: update hosting tips with meeting feedback

_posts/2020-01-29-#17487.md, _posts/2020-02-05-#18044.md
Begin WIP notes/questions, and update 2 links in n17487 questions.
As mentioned on irc, we could do this PR on 5th February, or later. It was just opened yesterday.
=> add n18044

assets/css/Roboto.css
#112 broke roboto font because of type. Fix it.
=> Fix roboto font link

_posts/2020-02-26-#17428.md
First pass at updating notes & questions. Review is definitely needed for language & formatting.
=> Notes & Questions for PR 17428

_posts/2020-03-04-#16981.md
Notes/questions for the upcoming meeting on PR16981.
=> Questions and Notes for 16981

_plugins/auto_logs_markup.rb
This should address the second part of https://github.com/bitcoin-core-review-club/bitcoin-core-review-club.github.io/pull/155#issuecomment-601716275
=> Leave trailing forward slashes in log links

_layouts/pr.html, _posts/2020-02-05-#18044.md, _posts/2020-02-12-#16902.md, _posts/2020-02-19-#17954.md, _posts/2020-03-04-#16981.md
This PR fixes the 404s and 301s found by the site links test in #45.
=> Fix site links

_includes/linkers/meetings-pages.md, _posts/2020-02-05-#18044.md, _posts/2020-02-12-#16902.md, _posts/2020-02-19-#17954.md, _posts/2020-03-04-#16981.md, assets/css/all.sass, meetings-prs.html
Initial proposal:
- displayed in descending order
- separated by groups of PR number / 1000
- links menu placement and styling TBD
=> Add meetings by PR number

_plugins/auto_logs_markup.rb
Closes #156. Color choice TBD :)
=> Add variable nick colors to logs

Makefile
See https://github.com/bitcoinops/bitcoinops.github.io/pull/386
=> Always rebuild index.html

_posts/2020-04-22-#17994.md
Thanks to @jonatack for pointing out s/necessary/necessarily/.
=> minor fixups for n17994

CONTRIBUTING.md, _posts/2020-04-29-#18038.md
Also update CONTRIBUTING.md. It's not necessary to make a local tag - just push it to the remote.
=> n18038 meeting log

_posts/2020-05-13-#17681.md
Adds basic notes for 17681. Russ will add full notes and questions early next week.
=> Add notes for n17681

_posts/2020-05-07-#18877.md
I don't know if you want to add this, here or somewher else, but I think it's a helpful resource.
(I reset my IRC connection at 19:01 so may have missed a line or two during that minute.)
=> n16442: add 2020-05-07 meeting log (BIP157)

_posts/2020-05-21-#19010.md
s/block headers/filter headers/
=> n19010: naming fixup in question 3

_posts/2019-05-01-#15557.md, _posts/2019-05-08-#10823.md, _posts/2019-05-15-#15834.md, _posts/2019-05-22-#15450.md, _posts/2019-05-29-#15741.md, _posts/2019-06-05-#16060.md, _posts/2019-06-12-#15996.md, _posts/2019-06-19-#15481.md, _posts/2019-06-26-#15681.md, _posts/2019-07-03-#15443.md, _posts/2019-07-10-#16244.md, _posts/2019-07-17-#15169.md, _posts/2019-07-24-#15713.md, _posts/2019-07-31-#15505.md, _posts/2019-08-07-#16345.md, _posts/2019-08-14-#16115.md, _posts/2019-08-21-#15931.md, _posts/2019-08-28-#15759.md, _posts/2019-09-04-#16512.md, _posts/2019-09-11-#16688.md, _posts/2019-09-18-#15204.md, _posts/2019-09-25-#16202.md, _posts/2019-10-02-#16401.md, _posts/2019-10-09-#16939.md, _posts/2019-10-23-#15934.md, _posts/2020-04-01-#18401.md, _posts/2020-04-15-#18521.md
...so that they match the labels in github.
=> Rationalize components

CONTRIBUTING.md
...as I did the opposite today when editing fjahr's notes ;)
=> CONTRIBUTING.md: use 3rd-person narrative in the notes

_data/settings.yml, code-of-conduct.md
Thanks to @Caralie for writing this!
=> Add code of conduct

_posts/2020-06-03-#16756.md
Notes and questions to follow.
=> Add n16756

_posts/2020-06-10-#19105.md, _posts/2020-06-17-#18242.md, _posts/2020-06-24-#18468.md
=> Add n19105, n18242, n18468

_posts/2020-06-17-#18242.md
Initial notes provided by @ariard. I've made some edits and modifications.
=> Add notes for n18242

_posts/2020-07-15-#19031.md
Made most of the suggested changes from #228.
=> 19031 edit

_posts/2020-07-22-#15644.md
=> Add review club notes for #15644

_posts/2020-08-19-#19509.md
=> Add Notes and Questions for 19509

_posts/2020-08-26-#19339.md
=> Add #19339

_posts/2020-09-16-#19845.md
Timely that Tor v2 deprecation is the day before the meeting!
=> n19845 notes and questions

_posts/2020-09-16-#19845.md
following up on feedback by vasild, jnewbery, and myself.
=> n19845 notes and questions improvements

_posts/2020-09-23-#19761.md
Thanks to @fanquake for the questions. I've added some very brief notes.
=> n19761: add notes and questions

_posts/2020-08-26-#19339.md
I'm terribly sorry for the inconvenience, but I changed my handles everywhere (this should be the only time I do this), and would really appreciate if the links could be updated. Thank you :)
=> Update gzhao's username

_posts/2020-02-12-#16902.md, _posts/2020-04-01-#18401.md, _posts/2020-07-29-#17977.md, _posts/2020-08-12-#17977-2.md, _posts/2020-09-02-#17977-3.md, _posts/2020-10-14-#19953.md
Notes and questions to follow
Also adds a new 'taproot' component, so that a list of all the taproot meetings is generated automatically. It's not strictly a component, but that field works well for general tags.
=> Announce meeting on 19953

_layouts/pr.html, _posts/2020-10-21-#19055-2.md
Also required a tweak to the layout template to make the link to https://github.com/bitcoin-core-review-club/bitcoin/tree/pr19055-2/ work.
=> Add meeting log for 19055-2

_posts/2020-11-04-#19905.md
Still thinking about questions and notes, so this is only a placeholder :sweat_smile:
=> Add _posts/2020-11-04-#19905.md

_posts/2020-11-25-#19858.md
for @jnewbery to review / edit / scrap / whatever
=> notes for 19858

_posts/2021-01-27-#20833.md
=> Add notes for #20833

_layouts/pr.html, _posts/2020-06-10-#19105.md, _posts/2020-10-21-#19055-2.md, _posts/2021-02-17-minisketch-#26.md
Also changes the "cryptography" category to "math and cryptography"
=> Announce minisketch n26

_posts/2021-02-24-#21224.md
Announcement, questions and notes for [21224](https://github.com/bitcoin/bitcoin/pull/21224)
=> ellemouton:pr21224

_posts/2021-02-24-#21224.md
Adds meeting log to 21224 "Halt processing of unrequested transactions"
...but I wasn't able to push the Bitcoin PR branch to the review club repo:
```sh
--> git push review-club 63103daf8:refs/tags/pr21224
remote: Permission to bitcoin-core-review-club/bitcoin.git denied to pinheadmz.
fatal: unable to access 'https://github.com/bitcoin-core-review-club/bitcoin.git/': The requested URL returned error: 403
```
=> Add n21225 meeting log

_posts/2021-03-10-#20861.md
=> notes for #20861

_posts/2021-03-24-#19438.md
=> Add notes for n19438

_posts/2021-03-24-#19438.md
Couple of extra questions for consideration.
=> Extra questions for n19438

_posts/2021-04-07-#21061.md
Still working, publishing to share with @amitiuttarwar :)
=> add notes for n21061

_posts/2021-04-14-#14707.md
@larryruane can you confirm that you want to host this PR?
=> Announce 14707

_posts/2021-04-14-#14707.md
I think the commit hash will need to change to reference the bitcoin-core-review fork.
=> add notes and questions for 14707

_posts/2021-03-24-#19438.md
=> n19438 notes/questions touch-ups

_posts/2021-04-28-#17331.md
PR: Use effective values throughout coin selection
=> Add notes and questions for n17331

_posts/2021-05-12-#21767.md
Apologies that these are late.
I'm going to merge now, but any post-merge review is appreciated!
=> Add notes and questions for n21767

_posts/2021-05-19-#18418.md
Recommended music pairing: https://www.youtube.com/watch?v=-33tz2b10Vc
=> add notes for n18418

_posts/2021-05-26-#22006.md
Questions follow soon <sup><sup><sup><sup><sup><sup>:tm:</sup> </sup> </sup> </sup> </sup> </sup>
=> add: #22006 on USDT

assets/css/1-tools/_code.scss, assets/css/all.sass
See ascii diagram at https://bitcoincore.reviews/22006
=> Style code in monospace

Rakefile
We have this question in every review club and it always requires going to a previous note to copy the text/link... maybe just include it in the TODO comment to save time?
=> include Question 1 and CONTRIBUTING.md link in template

_posts/2021-06-23-#22261.md
Recommended music pairing: https://www.youtube.com/watch?v=XImVRzK41kI
=> add notes for n22261

_posts/2021-07-28-#22155.md
music pairing: https://www.youtube.com/watch?v=fC71LJQVoK4 (let's get to subtractin)
=> add n22155

_posts/2021-07-28-#22155.md
questions were slightly confusing because they weren't pointing to the specific lines
=> a few n22155 links

_layouts/pr.html, _posts/2020-05-13-#17681.md, _posts/2021-05-19-#18418.md
(should be github.com/bitcoin/bitcoin/pull/{PR_no}
=> Fix github.com/bitcoin/bitcoin/pulls/{PR_no} links

_posts/2021-08-04-#22340.md
Not sure if i did the `commit: ` thingy correctly...
=> Add n22340 log

_posts/2021-09-15-#22677.md
recommended music pairing (POV you're validation.h breaking up with txmempool.cpp): https://www.youtube.com/watch?v=wfN4PVaOU5Q
=> add notes for n22677

_posts/2021-12-08-#23443.md
=> Minor updates to 23443

_posts/2021-12-15-#23724.md
Found your suggestions in https://github.com/bitcoin-core-review-club/website/pull/434#pullrequestreview-829103721 very helpful. Following up with a few more questions based on the suggestions. Danke!
=> Add additional questions for pr23724

_posts/2021-12-15-#23724.md
@glozow you'd need to push a tag of [0xB10C:2021-12-usdt-depends](https://github.com/0xB10C/bitcoin/tree/2021-12-usdt-depends) to bitcoin-core-review-club/bitcoin.git. I can't:
```
$ git push review-club 07057080640485b1d7564a7521976d25b5ff1a7d:refs/tags/pr23724
ERROR: Permission to bitcoin-core-review-club/bitcoin.git denied to 0xB10C.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
```
=> add irc logs for pr23724

_posts/2021-12-08-#10102.md
Started writing 10102 notes. Need to finish, clean up, and write questions
=> Add n10102 notes

_posts/2021-12-29-#20827.md
Still needs https://github.com/bitcoin/bitcoin/pull/20827/commits/24f3936337de3afb4fa56efc83009e2527d22df0 pushed :)
=> add irc logs for pr20827

_config.yml, _data/settings.yml, hosting.md, index.md
... and some minor comments to hosting.md.
=> Move CONTRIBUTING.md to hosting.md and build on live site

_posts/2022-02-02-#748.md
Based on #458. I tried to sort the further questions roughly such that the simplest and most relevant questions are first.
=> Add notes for secp256k1 #748

_posts/2022-01-19-#23201.md
=> n23201: add tag and update questions for new version of pr

_posts/2022-03-23-#21778.md
=> announce n21778

_posts/2022-02-16-#23542.md
=> add notes for n23542

_posts/2022-03-16-#24118.md
Please feel free to change the order of questions or add another if you can think of one. I am not sure I came up with the most interesting possible set.
=> Add notes and questions for n24118

README.md
=> update readme to point go hosting.md

_posts/2022-05-04-#24410.md
=> Add notes and questions for n24410

_posts/2022-05-18-#24148.md
Temporary update while finalizing full notes and questions.
=> Add preparatory resources to n24148

_posts/2022-05-18-#24148.md
This was meant to be force pushed as per darosior's comments in #506 but it looks like I [didn't actually commit](https://github.com/bitcoin-core-review-club/website/compare/8256a281662dcd0fead180ac0f2aa2965ed6b820..df89aad40fb433befcd73071c60d40f25e20bdc8) anything, fixed now.
=> n24148: fix bad commit message and add 2 questions

_posts/2022-05-18-#24148.md, _posts/2022-05-25-#24148-2.md
Added notes and questions for n24148-2, and retroactively added commit tag to n24148 too.
@darosior would you be able to have a look and see if everything's alright with you?
=> Add notes and questions for n24148-2

_posts/2022-06-29-#24832.md
Added post for ["#24832: Verify the block filter hash when reading the filter from disk."](https://github.com/bitcoin/bitcoin/pull/24832)
=> 24832 add post

_posts/2022-07-20-#25218.md
cc @furszy - feel free to have a look (no pressure). If you have any questions, comments or suggestions, happy to hear them!
=> Add notes for n25218

_posts/2022-07-27-#24858.md
cc @mruddy @mzumsande - suggestions, corrections, and additions are very welcome, if you have time, no pressure!
=> add notes for n24858

_posts/2022-09-21-v24-rc-testing.md
Hosted by @kouloumos - thank you!
=> announce v24rcs meeting

_posts/2022-09-07-#25957.md
=> announce n25957

_posts/2022-09-07-#25957.md
@theStack
Do you think it's okay to reference the previous notes? I couldn't think of anything different to say. But maybe something about descriptor wallets?
=> add notes for n25957

_posts/2022-09-07-#25957.md
I didn't add a commit hash (line 10) because there were no IRC log messages that referenced into the PR branch (only a few that referenced into bitcoin/bitcoin, but those are commit-hashed URLs), hope that's okay.
=> add n25957 logs

_posts/2022-09-14-#25991.md
Added logs, also fixed a small issue where I referred to the wrong function name (link is fine)
=> add logs for n25991

_posts/2022-10-19-#25515.md
https://github.com/bitcoin/bitcoin/pull/25515
@dergoegge
=> announce 25515

_posts/2022-10-12-#26158.md
https://github.com/bitcoin/bitcoin/pull/26158
=> announce n26158

_posts/2022-10-12-#26158.md
=> add notes for n26158

_posts/2022-10-19-#25515.md
@glozow @dergoegge 
I'm pretty happy with the notes but suggestions of course are welcome. The questions could possibly be added to or otherwise improved. Thanks to Niklas for some of the questions, and thanks to both of you for any comments, I welcome nits, nothing is too small! If you have permission to push, feel free to do so if I don't seem to be around (you can try and ping me on slack), I know I'm late with this, sorry.
=> add notes for n25515 

_posts/2022-10-19-#25515.md
and fixed a typo spotted by glozow
=> add logs for n25515

_posts/2022-11-09-#23897.md
cc @hebasto - feel free to have a look and/or leave any thoughts on these notes/questions, but no pressure!
=> add notes for n23897

_posts/2022-11-09-#23897.md
=> add link to Mastering Bitcoin book

_posts/2022-11-16-#25261.md
@stickies-v 
I hope I have the `commit:` tag correct; it's the current latest commit for this PR. The links into this PR's commits all specify commit hash (rather than just line number), which should be PR force-push-proof. But I thought there was something about cloning the current PR branch over to our (bitcoin-core-review-club) branch, but I'm not sure about this. I should learn now and then I can do it correctly from now on. Thanks.
=> add n25261 questions and notes (2022-11-16)

_posts/2022-11-23-#26152.md
I may add more questions. This PR is quite large 🤔
=> add n26152 notes

_posts/2022-11-23-#26152.md
Add logs and update min->max for effective value calculation
=> add logs for n26152

_posts/2022-12-14-#26631.md
=> announce n26631 - add coverage for dust mempool policy

_posts/2022-12-14-#26631.md
This is a checkpoint, I plan to add more, please don't merge yet. But do feel free to review what's here so far; I'm not planning on removing anything.
=> n26631 - add notes and questions

_posts/2023-01-11-#26742.md, index.md
=> Announce n26742

_posts/2023-01-11-#26742.md
cc @fjahr - very optional, but if you have any comments or suggestions please feel free to provide feedback!
=> add notes for n26742

_posts/2023-01-18-#26697.md
Please feel free to make corrections or add stuff; my availability is very limited for the next two days, so let's not wait that long for me to make changes. Thanks!
=> notes questions n26697

_posts/2023-01-18-#26697.md
I manually patched references to code in the PR, to instead reference the review club fork.
=> add n26697 irc log

_posts/2023-02-15-#26441.md
=> add n26441 announcement

_posts/2023-02-01-#26847.md
That was me trying to remember my shortcut for markdown preview :smile:
=> n26847: fix typo

_posts/2023-03-15-#27006.md
The PR doesn't have any labels so I've manually added the ["refactoring", "resource usage"] which seemed most appropriate.
FYI @furszy.
=> announce n27006

_posts/2023-03-08-#25325.md
Follow-on to #634, thanks @jonatack and @stickies-v!
=> n25325 expand notes to describe PBR

_posts/2023-03-08-#25325.md
See https://github.com/bitcoin-core-review-club/website/pull/634#discussion_r1126218011 (missing square brackets to imbed link), thanks @glozow!
=> n25325 touchup notes link

_posts/2023-03-15-#27006.md
cc @furszy - I've taken [your earlier comment](https://github.com/bitcoin-core-review-club/website/pull/633#issuecomment-1451875053) to phrase question 6 around it/allow for discussion.
=> add notes for n27006

_posts/2023-03-22-#27050.md
questions will follow later...
=> Add notes for 27050

_posts/2023-03-29-#26403.md
rough notes in case I run out of time later for prep
=> Add some notes for Ephemeral Anchors

_posts/2023-04-12-#27255-2.md
These comments by Pieter on the IRC channel after the meeting add context that seems useful and educational for readers.
=> Add Pieter Wuille addendum to 27255-2 meeting log

_posts/2023-04-19-#27039.md
cc @pinheadmz - feel free to leave any comments/suggestions if you like (but no pressure).
=> add notes and questions for n27039

_posts/2023-04-19-#27039.md
\+ fix title (remove component)
=> add logs for n27039

_posts/2023-04-26-#27460.md
=> notes and questions n27460 - Add importmempool RPC

_posts/2023-05-03-#27501.md
Nothing important, just some minor changes I'd already made during my earlier review of #670, but hadn't yet finished.
=> n27501 minor additions

_posts/2023-05-10-#26485.md
cc @ryanofsky feel free to leave any comments if you have them, but no pressure/need
=> add notes and questions for n26485

_posts/2023-05-17-#27600.md
@glozow I'm ambivalent on hosting this on 17th or 24th, so if you've been prepping your notes already then happy to go with that, then I'll just update mine to 24th?
I was a bit short on time so for notes just looked up earlier relevant review clubs and used @pinheadmz 's excellent PR notes.
=> Announce 27600

_posts/2023-05-24-v25-rc-testing.md
Hi, @stickies-v  I add the relevant notes, for the v25rc review club meeting.
Thanks for reviewing in advance.
=> add notes for v25rc-testing

_posts/2023-06-07-#27711.md
PR is still in draft, but I think the predecessor might get merged soon and regardless we can just focus on the non-base commits.
=> announce n27711

_posts/2023-06-28-#27307.md
=> announce n27307

_posts/2023-06-14-#27625.md
=> add notes for n27625

_posts/2023-08-02-#28122.md
Not sure what went wrong in #707, but some lines got garbled. Fixed (just using irccloud export and the script in https://bitcoincore.reviews/hosting)
=> n28122: fix log formatting issues

Rakefile
And add comment about not creating multiple per page.
=> Rakefile: don't create 2 meeting log blocks

_posts/2023-09-06-#28165.md
I did push a tag, but I'm using the links directly from the PR since it's been merged and links won't change.
=> n28165 notes

_posts/2023-11-15-v26-rc-testing.md
cc @m3dwards - thank you for hosting!
=> announce v26rc-testing

_posts/2023-11-15-v26-rc-testing.md
Draft until the testing guide is ready to - thanks @m3dwards!
=> add v26-rc-testing notes

_posts/2023-12-06-#28690.md
Thanks a lot for helping with my understanding of our build system as I was prepping for this @hebasto and @thecharlatan . Would greatly appreciate if you could have a look at this and lmk if you see any inaccuracies or room for improvement!
At the moment, I'm leaning towards doing this as a single review club, since I think the concepts are much more important than the code changes here (which is largely shuffling things around). Although it may be worthwhile to dive deeper into [1f98ed5e56230a61b699f669459e39fa101a1ca5](https://github.com/bitcoin/bitcoin/pull/28690/commits/1f98ed5e56230a61b699f669459e39fa101a1ca5) too, depending on feedback?
=> n28690: add notes and questions

_posts/2024-01-03-#28956.md
@glozow n28956 has no labels yet, P2P and Consensus seem most appropriate (checked with @dergoegge) so I added them here - would you mind adding them on the bitcoin repo too pls?
=> announce n28956

_posts/2024-01-03-#28956.md
=> n28956: add notes and questions

_posts/2024-03-06-bitcoin-inquisition-#39.md, _posts/2024-03-13-bitcoin-inquisition-#45.md
Draft while figuring out scheduling.
=> announce inquisition n39 and n45

_posts/2024-03-06-bitcoin-inquisition-#39.md
First draft of questions and notes for [bitcoin-inquisition-39](https://github.com/bitcoin-inquisition/bitcoin/pull/39).
=> add notes and questions for bitcoin-inquisition-39

_posts/2024-03-06-bitcoin-inquisition-#39.md
@glozow Apologies for the last minute change.
Added two more "easy" questions. And squashed some of the script verify flag questions into just one question.
=> updates to n39

_posts/2024-05-01-#30000.md
Simple one, since this is so late
=> announce n30000

_posts/2024-06-05-#30132.md
cc @TheCharlatan - if you're able to have a quick look that'd be great, but no pressure if not.
=> add notes and questions for n30132

contrib/new_post.py
=> contrib: use user.ghtoken for github api requests

_posts/2024-07-03-#29775.md
Maybe it's a bit many questions for the time we have. I would just skip some of them in the meeting if we are not moving fast enough but I can also kick some out or mark them as optional if you prefer that.
=> Add notes and questions for #29775 (Testnet 4)

_posts/2024-09-11-v28-rc-testing.md
Note: I've add the discussion post-#endmeeting too since it seems relevant.
Thanks again for hosting this @rkrux!
=> add logs for v28rc testing

_posts/2024-11-06-#30239.md
cc @tdb3 - thank you for hosting!
=> announce n30239

_posts/2024-11-06-#30239.md
=> add logs for n30239

_posts/2025-02-05-#31363.md
```
___           ___           ___           ___           ___           ___           ___     
/\  \         |\__\         /\  \         /\  \         /\  \         /\  \         /\__\    
\:\  \        |:|  |       /::\  \       /::\  \       /::\  \       /::\  \       /:/  /    
\:\  \       |:|  |      /:/\:\  \     /:/\:\  \     /:/\:\  \     /:/\:\  \     /:/__/     
/::\  \      |:|__|__   /:/  \:\  \   /::\~\:\  \   /::\~\:\  \   /::\~\:\  \   /::\  \ ___ 
/:/\:\__\ ____/::::\__\ /:/__/_\:\__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/\:\  /\__\
/:/  \/__/ \::::/~~/~    \:\  /\ \/__/ \/_|::\/:/  / \/__\:\/:/  / \/__\:\/:/  / \/__\:\/:/  /
/:/  /       ~~|:|~~|      \:\ \:\__\      |:|::/  /       \::/  /       \::/  /       \::/  / 
\/__/          |:|  |       \:\/:/  / …
```
=> announce n31363

_posts/2025-03-05-#31405.md
=> announce n31405

_posts/2025-03-05-#31405.md
Also fix `InvalidBlock()` -> `InvalidateBlock()` typo.
=> Add logs for n31405

_posts/2025-04-16-#29532.md
=> add notes and questions for n29532

assets/css/all.sass
Change colors to more eye friendly as now the contrast is too heavy.
More info in this https://github.com/bitcoin-core-review-club/website/pull/810#issuecomment-2790082860
=> Use more eye-friendly colors for the dark theme

_posts/2025-05-07-#31375.md
These were mostly generated by [o3](https://chatgpt.com/share/6808496f-6cd4-800a-984a-11775025dd30) with pruning & editing by me
=> add notes and questions for n31375

_posts/2025-05-14-#32317.md
I'm going to add some more meat to the notes, and maybe add a question or two later on, but I think this is already enough to online for now?
cc @TheCharlatan
=> add notes and question for n32317

_posts/2025-05-14-#32317.md
Added a few more notes on the UTXO set and the approach taken (and fixed 2 style issues)
cc @TheCharlatan
=> n32317: improve notes

_posts/2025-05-28-#32051.md
Thanks for hosting, @jonatack !
=> announce n32051

_posts/2025-06-04-#30605.md
=> announce n30605
