- index.html
Remove "C++ Primer Plus". Here are 3 links that explain why:
- https://www.reddit.com/r/cpp/comments/13g6s1/which_c_primer_book_is_better/
- https://www.quora.com/Between-C++-Primer-Plus-and-C++-Primer-which-is-better-and-why
- http://www.cplusplus.com/forum/beginner/106097/
[C++ Primer, 5th Edition](https://www.amazon.com/Primer-5th-Stanley-B-Lippman/dp/0321714113/) and the dated but compact and well-regarded [Accelerated C++](https://www.amazon.com/Accelerated-C-Practical-Programming-Example/dp/020170353X/) are introductory books I've worked through and can recommend. That said, individual readers' needs vary, and it may be best to simply provide a link to this (quite good) list of books organised by category:
- https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-l …
> Improve/simplify C++ book recommandations

- README.md
Trivial update to the README to:
1. update/simplify the introductory description because the website is no longer only about upcoming meetings; it now contains a history and log of past meetings, and
2. add the website URL to enable easily navigating from the repository to the website (something I've been missing, so this is the real reason).
Click here here to test this change:
https://github.com/jonatack/bitcoin-core-review-club.github.io/tree/add-website-url-to-readme-doc
Cheers!
> doc: update README intro and add website URL

- _layouts/pr.html
- _posts/2019-05-01-#15557.md
- _posts/2019-05-08-#10823.md
- _posts/2019-05-15-#15834.md
- _posts/2019-05-22-#15450.md
- _posts/2019-05-29-#15741.md
- _posts/2019-06-05-#16060.md
- _posts/2019-06-12-#15996.md
- _posts/2019-06-19-#15481.md
- _posts/2019-06-26-#15681.md
- _posts/2019-07-03-#15443.md
- _posts/2019-07-10-#16244.md
- _posts/2019-07-17-#15169.md
- _posts/2019-07-24-#15713.md
- _posts/2019-07-31-#15505.md
- _posts/2019-08-07-#16345.md
- _posts/2019-08-14-#16115.md
- _posts/2019-08-21-#15931.md
- _posts/2019-08-28-#15759.md
- _posts/2019-09-04-#16512.md
- _posts/2019-09-11-#16688.md
- _posts/2019-09-18-#15204.md
- _posts/2019-09-25-#16202.md
- _posts/2019-10-02-#16401.md
- assets/css/all.sass
- index.html
- previous_meetings.html
I've only implemented this for the next meeting, but the idea is:
- reduce boilerplate content in pages
- tag meetings by component and host so we can add indexes for those later (eg https://bitcoin-core-review-club.github.io/component/wallet would list all of the wallet PRs that we've discussed)
> Add pr page template and page variables

- index.html
- meetings-components.html
- meetings-hosts.html
- meetings.html
1. Fix the meetings-components and meetings-hosts header from "Previous meetings" to "Meetings" since they list all meetings.
2. In the meetings by date page, list all of the meetings instead of the past ones, to keep the meetings listings consistent.
3. In the home page, above the listing of the last 4 meetings, change the title from "Previous meetings" to "Recent meetings", and update the "See all previous meetings" to "See all meetings".
This PR should make everything consistent for now, while figuring out how the site will evolve.
> Update the meeting listings headers

- _posts/2019-10-09-#16939.md
This PR proposes one possible PR for the Review Club PRs. That said, we've done several p2p PRs lately and it could be time to look at a different type of PR.
This one actually involves reviewing two short PRs, one merged and one open, by sipa and ajtowns. Is there a bug to be fixed?  *You make the call.*
The host would need to be filled in and the notes are only preliminary.
> Add n16939

- Rakefile
rather than by undesired components currently as per discussion in PR #77.
LMK if any components used in the current repo tags are missing.
> Filter components by desired for `rake posts:new`

- _config.yml
- _layouts/pr.html
- index.md
I sent this week's meeting link to some coworkers, they asked me how to join the meeting!
This PR adds the where & when to each meeting page:
> layout: include time and place on PR page

- Rakefile
- _posts/2019-12-11-#16702.md
- _posts/2019-12-18-#17639.md
to handle PR titles containing double quotes, like for next week's PR 17639, without making Jekyll halt. I went with simply stripping the double quotes. Alternatively, we could convert the double quotes to single quotes. I didn't find it as aesthetic in this case, but it could be an option.
Also made a minor fixup in yesterday's meeting notes.
> Add n17639 and update rake posts:new task

- index.md
This should be reverted when the Jan 8 meeting is announced.
> Add a placeholder for holiday break

- Rakefile
A few force pushes to simplify the change and add comments.
Added logging to see the results while running `rake posts:new`.
Handle some edge cases seen while testing.
> Remove component from PR title in rake posts:new

- _posts/2020-01-22-#17477.md
1st commit:
- mark meeting post as `past`
- fix minor formatting in the notes `text` block
- add @jnewbery meeting question to the prep questions
2nd commit:
- add meeting log
> n17477 meeting log and updates

- CONTRIBUTING.md
- Rakefile
- index.md
- Add `commit` field and meeting log section to the files generated by the `rake posts:new" task
- Propose steps for adding PR tags and commits in CONTRIBUTING.md
- Propose moving the maintainer info to the bottom of CONTRIBUTING.md
The updated version of CONTRIBUTING.md can be viewed here:
https://github.com/jonatack/bitcoin-core-review-club.github.io/blob/add-tag-commit-hash-info-to-CONTRIBUTING/CONTRIBUTING.md
> Update new post file and maintainer info

- _includes/linkers/meetings-pages.md
- _layouts/pr.html
- _posts/2019-05-01-#15557.md
- _posts/2019-05-08-#10823.md
- _posts/2019-05-15-#15834.md
- _posts/2019-05-22-#15450.md
- _posts/2019-05-29-#15741.md
- _posts/2019-06-05-#16060.md
- _posts/2019-06-12-#15996.md
- _posts/2019-06-19-#15481.md
- _posts/2019-06-26-#15681.md
- _posts/2019-07-03-#15443.md
- _posts/2019-07-10-#16244.md
- _posts/2019-07-17-#15169.md
- _posts/2019-07-24-#15713.md
- _posts/2019-07-31-#15505.md
- _posts/2019-08-07-#16345.md
- _posts/2019-08-14-#16115.md
- _posts/2019-08-21-#15931.md
- _posts/2019-08-28-#15759.md
- _posts/2019-09-04-#16512.md
- _posts/2019-09-11-#16688.md
- _posts/2019-09-18-#15204.md
- _posts/2019-09-25-#16202.md
- _posts/2019-10-02-#16401.md
- assets/css/all.sass
- meetings-authors.html
Adds a `meetings-authors` page to allow seeing PRs sorted by author. This was my motivation for this feature. It's basically a mix of the work already done for the components and hosts.
Added authors to 4 of the meetings for testing.
Handles one or multiple authors per PR.
Displays the authors in the PR layout if any are present, with links to the author's PRs and GitHub, like for meeting hosts.
> Add authors index

- _plugins/auto_logs_markup.rb
Adds 1 or 2 seconds to the build but looks great. Whitelisted the uri schemes, otherwise any word ending with a colon was being turned into a link. Nevertheless, much cleaner to use the Ruby URI standard library than futzing around with regexes for this.
> Convert URIs in meeting logs to HTML links

- Makefile
No need to clean jekyll when doing a `make preview`. Just run jekyll serve --incremental so we don't rebuild everything.
This brings build times down from ~8s to <0.5s.
`make build` still does a clean since it's not doing an incremental build so we might as well clean. Also add a `make clean` target.
Historic note: I copied our makefile from optech, and Dave copied that makefile from bitcoin.org, where he needed to use clean because some of their custom plugins didn't work well with incremental builds.
> Don't clean jekyll between previews

- _plugins/auto_logs_markup.rb
Found a few cases where a link could be broken if followed by trailing punctuation or brackets, for example:
- https://bitcoincore.reviews/16981.html#l-135
- https://bitcoincore.reviews/16939.html#l-46
and also see a `file:` turned into a useless link, so removed "file" from the schemes, as well as 'ftp' and 'mailto' until we see those actually needed.
> Clean up links in meeting logs

- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- test/test_helper.rb
- test/test_rake_posts_new.rb
- test/test_site_content.rb
TL|DR:
```
$ bundle update && gem install curb
$ make preview (if running the links test on the local server) 
$ rake
```
This PR sets up testing in a minimal way using Minitest, a simple, fast, tiny mini-framework in pure Ruby with no magic or DSL. It also adds a pretty test reporter because it's much nicer and a tiny dependency.
This allows running the tests from the command line with `rake test` or simply `rake`. Individual test files or cases can be run as well as per the comments in the Rakefile. There are integrations available for various editors, including vim and emacs, to run this from within the editor environment. 
--------
NEW: Added a test to check all the links in the site -- either locally after running `make preview` (default), or on the website in production, and display …
> Add test setup and test all site links

- _plugins/auto_logs_markup.rb
- test/test_site_content.rb
Add a one-line test and a two-line fix for empty nicks like https://bitcoincore.reviews/17428.html#l-242
```
242 13:52 <> * luke-jr , before running out of time, wonders...
```
To run the test:
```
$ make preview
$ rake TEST=test/test_site_content TESTOPTS=--name=test_site_displays_no_empty_nicks
```
or swap lines 14 and 15 in `test_site_content.rb` to run the test on the production website:
```
$ rake TEST=test/test_site_content TESTOPTS=--name=test_site_displays_no_empty_nicks
```
The test currently fails in production and passes locally in the PR branch.
This PR is based on #45.
> Add test and fix for empty nicks in site content

- _posts/2020-03-18-#18113.md
While running the tests to check #166, they found a link that just went from 200 to 404 due to a force push in the PR. This kind of fix could arguably be automated at some point.
> n18113: fix link that changed from 200 to 404

- _posts/2020-04-01-#18401.md
The commits referenced were outdated. I am pretty sure I got the right ones, but please check again, one of the commits referenced seems to have been split.
> Fix 18401 future commit links

- _posts/2020-04-08-#18453.md
- Remove hard/soft terminology.
- Remove listing of wallet RPCs (attendees can look these up easily)
> Minor changes to n18453

- _config.yml
There are some files that get included in the site build that shouldn't be, eg go to https://bitcoincore.reviews/Makefile. Exclude them.
> Exclude non-site files from build

- Rakefile
as per https://github.com/bitcoin/bitcoin/labels
Some of these, like `Data corruption`, `Privacy`, and `Refactoring`, are arguably not codebase components but may be practical or the only label.
> Update GitHub labels used by Bitcoin Core

- index.md
Use a counter variable so the 4 most recent past
meetings are always shown on the home page.
> Fix past meetings counter

- _posts/2020-06-24-#18468.md
Noticed the component tag was creating a second `refactor` component type in https://bitcoincore.reviews/meetings-components. A quick look at the GitHub PR shows that `refactoring` is still the correct tag.
While fixing it up, did a quick grammar and presentation pass through the notes and questions. Don't hesitate to drop that commit.
> n18468  component tag fix and notes tidy-ups

- _posts/2020-08-26-#19339.md
Fix one semi-confusing link between two sections in line 226.
> n19339 post-meeting url fixups

- _posts/2020-11-18-#20079.md
Fix two small typos in n20079:
- `send` -> `sent`
- `disconecting` -> `disconnecting`
> Fix two small typos in n20079

- _posts/2021-02-10-#18261.md
One of the review clubs that lightlike/mzumsande hosted was mapped to the irc handle instead of github.
> Fix a host's handle

- _includes/head.html
- _layouts/default.html
- assets/css/1-tools/_code.scss
- assets/css/all.sass
Offering this for late night review club crammers to make the site easier on the eyes. For IRC logs, I switched out a few colors for better contrast against the dark background.
Here's some examples screen shots showing main page, IRC log, and a `code` block...
##
##
##
> Redecorate with dark theme

- assets/css/all.sass
There is a white edge on large screens when darkmode is enabled. (See screenshot)
(Not sure if this is a concern but this fix would make lines longer on screens that are wider than 2250 pixels.)
> Remove max-width from site-container

- _posts/2021-02-17-minisketch-#26.md
- _posts/2021-03-03-minisketch-#26-2.md
as they currently appear the same apart from the date in the meetings listings.
> Differentiate the titles of Python Minisketch meetings 1 and 2

- _posts/2021-05-19-#18418.md
While I was reviewing the question about `CoinEligibilityFilter.include_partial_groups` vs `CoinSelectionParams.avoid_partial_spends`, I realized I mixed them up in the notes 🤦 fixed that and added links.
Also, I felt like the multiple choice thing in Q2 was a little weird, so I changed it to a more discussion-y question.
> fix inaccurate note and weird question in 18418 notes

- _layouts/default.html
- assets/css/all.sass
Text is more difficult to read when the columns are very wide. Limit the maximum website width to 1200px to prevent very long lines.
> Add max-width attribute to limit page width

- _posts/2021-12-01-#23614.md
Line 50 in the IRC log for n23614 currently looks odd:
Correcting the timestamp should hopefully fix that.
> fix n23614 irc log (broken timestamp)

- _posts/2021-11-24-#23512.md
components are case-sensitive (should all be downcased if using the rake command)
before:
after:
> consolidate TX fees and tx fees components

- _config.yml
- _layouts/pr.html
- index.md
- your-first-meeting.md
We lost the channel name from the front page somewhere along the way.
> Show irc channel name more prominently

- _posts/2020-03-18-#18113.md
- _posts/2020-04-15-#18521.md
- _posts/2020-09-16-#19845.md
- _posts/2021-03-17-#21142.md
- _posts/2021-07-28-#22155.md
- _posts/2021-08-11-#20295.md
- _posts/2021-09-01-#22675.md
- _posts/2021-11-24-#23512.md
- _posts/2021-12-15-#23724.md
- _posts/2022-02-16-#23542.md
Redundant info (already in the component tags) and clutters the titles.
> remove components from PR titles

- _posts/2022-03-30-v23-rc-testing.md
I'm still getting some review and feedback on the guide, should be finalized on Monday. I'll push it to bitcoin-devwiki then, and update the link and remove the `WIP` disclaimer here. Not sure if you prefer to merge already or wait until it's live on the wiki?
> Update meeting notes for v23-rc-testing

- hosting.md
Should be faster than doing it manually. Every. Time. Again.
Discards everything before the _last_ `#startmeeting`  and the subsequent `#endmeeting` found in the logs; removes joined/left messages and converts datetime into timestamps.
Converts
```
...
[2022-05-11 16:59:46] <larryruane> thanks
[2022-05-11 17:00:23] <dongcarl> #startmeeting
[2022-05-11 17:00:30] <dongcarl> hello all
...
[2022-05-18 16:59:09] → Bayer joined (~Bayer@pop.92-184-117-40.mobile.abo.orange.fr)
[2022-05-18 16:59:47] → svav joined (~svav@82-69-86-143.dsl.in-addr.zen.co.uk)
[2022-05-18 17:00:11] <stickies-v> #startmeeting
[2022-05-18 17:00:16] <svav> Hi
...
[2022-05-18 17:05:33] <kouloumos> read the notes, didn't review code
[2022-05-18 17:05:33] → Azor joined (~Azor@200.109.50.144)
[2022-05-18 17:05:44] <svav> An …
```
> Add shell command to sanitize logs from IRCCloud

- _posts/2022-09-28-v24-rc-testing.md
@kouloumos and @glozow because RC1 will be ready later than expected, pushing back the testing review club by one week. Thanks for taking over the slot for the 21st, glozow!
> push back v24-rc one week later

- _posts/2022-10-12-#26158.md
The `static_cast` currently isn't showing properly on the website:
> fix formatting for n26158

- _posts/2022-10-26-#26265.md
At the review club on Oct 26, Murch uploaded an image, and I just happened to notice that this doesn't format well, at least on my browser (chrome):
https://bitcoincore.reviews/26265#l-71
The link isn't clickable, is somewhat mangled, and Murch's name is dropped off. I don't think it's worth automating this type of fixup (there are no other instances of this problem in the entire review club history), but if starts happening more often, we can consider it.
> manual fix for "Murch uploaded an image" 2022-10-26 n26265

- _plugins/auto_logs_markup.rb
- _posts/2022-10-26-#26265.md
Fixes the IRC nickname parsing issue reported in #584 and reverts the manual fix since it is no longer necessary.
The updated nickname regex now matches the data _after_ the time stamp (`IRC_NICK.match(line[TIME_SIZE_PLUS_1..-1]).to_s`) and requires the `IRC_NICK` pattern to be at the beginning (`^`) of that (shortened) string, while allowing additional leading whitespaces in a non-capturing group (`(?:\s*)`). The leading whitespaces tolerance is because [n24098](https://github.com/bitcoin-core-review-club/website/blob/master/_posts/2022-02-23-%2324098.md?plain=1) has double whitespaces between timestamp and nickname (guess who added those logs?!). Instead of just fixing the logs in n24098, I think it makes sense to not have the parsing be unnecessarily strict?
cc @LarryRuane for …
> Improve IRC nickname parsing

- Rakefile
probably not the most elegant way to do this, so happy for suggestions on how to improve it!
without this, the post will fail to build when running `make preview`, but it fails with a really obtuse error:
```
Configuration file: /home/josibake/website/_config.yml
Source: /home/josibake/website
Destination: /home/josibake/website/_site
Incremental build: enabled
Generating... 
Jekyll Feed: Generating feed for posts
Liquid Exception: Could not locate the included file 'ERROR_92_MISSING_TOPIC_CATEGORY' in any of ["/home/josibake/website/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in meetings-components.html
```
took me longer than id like to admit to troubleshoot it.
at least the warning will point people in the …
> print a warning when there are no labels from github

- Rakefile
Without components, the project cannot build. With this change, the user is queried to manually input components on the command line if none are found. The input is sanitized to ensure data stays in line with `COMPONENTS`.
Follow up on #645
> Ask for user input when no components are fetched from GitHub

- README.md
- test/test_rake_posts_new.rb
This test just asserts true and exits. I think it was originally intended to test the `rake posts:new` function, but was never implemented (see #45)
> Remove empty test_rake_posts_new test

- _data/social-media.yml
- _includes/header.html
- _includes/social-media-links.html
- assets/css/all.sass
- index.md
Partially addresses #625, implementing jnewbery's [suggestion](https://github.com/bitcoin-core-review-club/website/issues/625#issuecomment-1481089733) to include favicons for our Twitter and Atom feed on the site header.
My jekyll and frontend skills are minimal, so I'm very open to suggestions on implementing this in a cleaner way, although I think it's fairly maintainable as is. To edit the icons, one can just update `_data/social-media.yml`.
> Add RSS and Twitter favicons

- _posts/2023-04-05-#27255.md
MiniScript uses `d` for the "dissatisfiable" _property_, and `d:X` for the `DUP IF [X] ENDIF` _wrapper_.  I don't think the question meant to refer to the "dissatisfiable" property, but to the wrapper?
cc @josibake
> n27255: ambiguate between wrapper d: and property d

- _posts/2023-04-19-#27039.md
by removing special characters added in the meeting log last week. These don't appear to be displayed in the HTML page at https://bitcoincore.reviews/27039#l-158.
The URL https://bitcoincore.reviews/feed.xml currently errors with:
```
XML Parsing Error: not well-formed
Location: https://bitcoincore.reviews/feed.xml
Line Number 253, Column 412:
&lt;table class=&quot;log-line&quot; id=&quot;l-158&quot;&gt;&lt;tr class=&quot;log-row&quot;&gt;&lt;td class=&quot;log-lineno&quot;&gt;&lt;a href=&quot;#l-158&quot;&gt;158&lt;/a&gt;&lt;/td&gt;&lt;td class=&quot;log-time&quot;&gt;17:45 &lt;/td&gt;&lt;td&gt;&lt;span class=&quot;log-nick&quot; style=&quot;color:cadetblue&quot;&gt;&amp;lt;sipa&amp;gt;&lt;/span&gt;&lt;span class=&quot;log-msg&quot;&gt; Exactly. -reindex-chainstate is exactly …
```
> Fix XML parsing error in Atom feed URL

- _posts/2023-05-24-v25-rc-testing.md
@ismaelsadeeq I'll make the announcement already, and then you can add the link to the testing guide and some notes (if relevant) when finished with that?
See e.g. https://bitcoincore.reviews/v24-rc-testing and https://bitcoincore.reviews/v23-rc-testing
> announce v25rc-testing

- _posts/2023-06-21-#27748.md
We just announced n26697 (#696), but we already covered that PR back on [Jan 18, 2023](https://github.com/bitcoin-core-review-club/website/blob/master/_posts/2023-01-18-%2326697.md). It has changed substantially since then, so I considered reviewing it in its current form but decided against it, so we'll go with 27748 instead. Sorry about the confusion. I'll get the notes and questions done in the next few days.
> june 21 2023 - announce n27748 (was n26697)

- _posts/2023-08-02-#28122.md
fixes #710, which we should do asap
The plugin runs per irc block so it restarts the log line number for the second meeting log block.
This puts everything under 1 block, means the numbering continues. Tbh I like this better as it feels more like a continuation of the same meeting on a different day.
This is how we did it for other review club PRs with 2 meetings: https://bitcoincore.reviews/16981#l-216
I'll open a separate PR for fixing the rakefile, where we can talk about whether this is the best solution for multiple meeting logs.
> n28122: dont create 2 irc blocks

- index.md
The bitcointechtalk links return a "Misdirected Request" error, replace with (what I think are) the underlying posts.
Thanks @aassoiants for spotting!
> Fix dead links on homepage

- _posts/2023-09-06-#28165.md
Looks like hardcoding the numbers in #716 didn't help, adding a kramdown tag.
> n28165: continue numbering across meetings

- _posts/2023-09-06-#28165.md
Not adding logs because no material was covered.
> wrap up n28165 meeting

- _config.yml
Providing an easy way for people to join via web client is nice and less discouraging to people who don't normally use irc. The original kiwi irc link doesn't work anymore, but this new link seems to work.
> replace broken web client link

- _posts/2024-09-11-v28-rc-testing.md
The testing guide is still wip, but we can announce now to schedule the meeting.
> add announcement for v28 rc testing

- contrib/new_post.py
subprocess.run() does not throw a CalledProcessError when the process exits with a non-zero exit code, unless `check=True` is set. This means that when the `option` key is not found, an empty string is returned instead, causing a wrong ghtoken to be used for the `Authorization` header.
This leads to:
```
% ./contrib/new_post.py 30239 <author> 2024-11-06
Github returned error HTTP Error 401: Unauthorized
```
Fix this and simplify the code by using the convenience function `subprocess.check_output()` instead.
Addresses https://github.com/bitcoin-core-review-club/website/pull/764#issuecomment-2432690897
> contrib: bugfix: allow empty user.ghtoken

- .dockerignore
- Dockerfile
- Makefile
- README.md
- docker-compose.yml
Adding Docker support makes it much easier for people to preview the website when making changes.
From the updated README:
```
You'll need [Docker](https://docs.docker.com/get-docker/) and [Docker
Compose](https://docs.docker.com/compose/install/) installed.
* Clone the repository and go into the directory
* Run `docker compose up` to start the development server with live
reload
* Go to http://localhost:4000
```
(Note: to test this PR, it might be wise to add `--build` to the command, in case the Dockerfile changes: `docker compose up --build`)
> Add Docker support and instructions

- _includes/social-media-links.html
- _layouts/default.html
- assets/css/all.sass
According to https://caniuse.com/?search=prefers-color-scheme, >96% of users have a browser that supports prefers-color-scheme.
Simplify UX, clean up code by following the browser/system dark mode settings and remove the manual toggle.
Also fixes #678 by rendering icons as white in dark mode.
Tested on Chrome and Firefox.
Alternative to #809
> style: automatically set dark mode, and fix invisible icons
